-- CreateTable
CREATE TABLE "User" (
    "userId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "group" TEXT NOT NULL,
    "createAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "submitAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Image" (
    "imageId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "imageLocation" TEXT NOT NULL,
    "dataLocation" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Answer" (
    "answerId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "userId" INTEGER NOT NULL,
    "imageId" INTEGER NOT NULL,
    "answer" TEXT NOT NULL,
    "startAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "submitAt" DATETIME NOT NULL
);
